apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: external-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: nginx:alpine
          env:
            - name: MOCKAPI_PROJECT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mock-api-secret-app
                  key: MOCKAPI_PROJECT_SECRET
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
