apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mock-api-secret
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: mock-api-secret-app
    creationPolicy: Owner
  data:
    - secretKey: MOCKAPI_PROJECT_SECRET
      remoteRef:
        key: lab/kubernetes
        property: MOCKAPI_PROJECT_SECRET