apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: labs
data:
  greating-message: "hello-world"
  drink: {{ .Values.favorite.drink | default (printf "%s-tea" (include "fullname" .)) }}
  food: {{ .Values.favorite.food | upper | quote }}
