apiVersion: v1
kind: Namespace
metadata:
  name: "k3dlocal"
  labels:
    projeto: "projeto-k3d-local"
    env: "local"

---
apiVersion: v1
kind: Namespace
metadata:
  name: "argocd"
  labels:
    projeto: "projeto-k3d-local"
    env: "local"