apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: hashicorp/http-echo:0.2.3
          args: ["-text=frontend"]
          ports:
            - containerPort: 5678
          resources:
            requests: # Minimum resources needed by the container
              cpu: "100m"
              memory: "128Mi"
            limits: # Maximum resources the container can use
              cpu: "200m"
              memory: "256Mi"
