name: Terraform Destroy on Label "destroy-lab"

on:
  push:
    branches:
      - demo_aws_vultr_terraform_destroy

jobs:
  terraform-execute-aws-vultr-demo-destroy:
    runs-on: ubuntu-latest
    env:
      TF_LOG: TRACE
      TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve