name: AWS S3 LS Test on Push

on:
  push:
    branches:
      - demo_workflow_aws_s3 # Trigger this workflow only when pushes happen on the 'demo_workflow_aws_s3' branch

jobs:
  test_s3_ls:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to checkout your code

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # Action to configure AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # AWS Access Key ID from GitHub Secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS Secret Access Key from GitHub Secrets
          aws-region: us-east-1 # Specify your AWS region (e.g., us-east-1, eu-west-1, etc.)

      - name: Test AWS S3 LS
        run: |
          echo "Attempting to list S3 buckets on aws..."
          aws s3 ls s3://bucket-kubernetes-labs-terraform-state
          if [ $? -eq 0 ]; then
            echo "AWS S3 LS command executed successfully."
          else
            echo "Error: AWS S3 LS command failed."
            exit 1 # Exit with a non-zero code to indicate failure
          fi