name: Demo Terraform save tfstate on AWS S3

on:
  push:
    branches:
      - demo_aws_terraform_v2

jobs:
  terraform-execute:
    runs-on: ubuntu-latest
    env:
      TF_LOG: TRACE
      TF_VAR_VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -output=tfplan
          
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan